services:
  app:
    build:
      context: ../
      dockerfile: ./deploy/dockerfile
    ports:
      - ${PORT}:8000
    env_file: ../.env
    command: [ "uvicorn", "--factory", "app:create_app", "--host", "0.0.0.0", "--port", "8000" ]
    restart: on-failure
    healthcheck:
      test: curl --fail http://localhost:8000/api/v1/utils/health || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    depends_on:
      database:
        condition: service_healthy
  database:
    image: postgres
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${POSTGRES_DATABASE} -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    environment:
      PGDATA: /var/lib/postgresql/data/${POSTGRES_DATABASE}
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:5432
    env_file: ../.env
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: